name: Ejecutar scraper Kinepolis

on:
  schedule:
    - cron: "*/30 * * * *"   # cada 30 minutos
  workflow_dispatch:        # permite ejecutarlo manualmente

jobs:
  scrape:
    runs-on: ubuntu-latest

    steps:

      - name: Clonar repositorio
        uses: actions/checkout@v4

      - name: Instalar Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Instalar dependencias
        run: |
          pip install -r requirements.txt
          playwright install chromium

      - name: Ejecutar scraper
        run: |
          python scraper.py

      - name: Commit y push de datos
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "actions@github.com"

          git add ocupacion_kinepolis.csv metadata.json
          git commit -m "actualización automática datos" || echo "sin cambios"
          git push